import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/employeedb.png';
import imageDark from '@/assets/templates/employeedb-dark.png';

const now = Date.now();

export const firestoreTodosDb: Template = {
    slug: 'firestore-todos',
    name: 'Firestore Todos',
    shortDescription: 'Todo application schema for Firestore',
    description:
        'A NoSQL todo application schema for Firestore featuring users, todos, categories, and tags with document-based data structure.',
    image,
    imageDark,
    tags: ['Firestore', 'NoSQL', 'Firebase'],
    featured: true,
    diagram: {
        id: 'firestore_todos_db',
        name: 'firestore-todos',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.FIRESTORE,
        tables: [
            {
                id: 'firestore_users_collection',
                name: 'users',
                x: -250,
                y: 0,
                fields: [
                    {
                        id: 'firestore_users_id',
                        name: 'id',
                        type: { id: 'string', name: 'string' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_users_email',
                        name: 'email',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_users_displayName',
                        name: 'displayName',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_users_photoURL',
                        name: 'photoURL',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_users_createdAt',
                        name: 'createdAt',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_users_updatedAt',
                        name: 'updatedAt',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'firestore_todos_collection',
                name: 'todos',
                x: 150,
                y: 0,
                fields: [
                    {
                        id: 'firestore_todos_id',
                        name: 'id',
                        type: { id: 'string', name: 'string' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_userId',
                        name: 'userId',
                        type: { id: 'reference', name: 'reference' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_title',
                        name: 'title',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_description',
                        name: 'description',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_completed',
                        name: 'completed',
                        type: { id: 'boolean', name: 'boolean' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_priority',
                        name: 'priority',
                        type: { id: 'number', name: 'number' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_categoryId',
                        name: 'categoryId',
                        type: { id: 'reference', name: 'reference' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_dueDate',
                        name: 'dueDate',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_tags',
                        name: 'tags',
                        type: { id: 'array', name: 'array' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_metadata',
                        name: 'metadata',
                        type: { id: 'map', name: 'map' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_createdAt',
                        name: 'createdAt',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_todos_updatedAt',
                        name: 'updatedAt',
                        type: { id: 'timestamp', name: 'timestamp' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'firestore_categories_collection',
                name: 'categories',
                x: 150,
                y: 350,
                fields: [
                    {
                        id: 'firestore_categories_id',
                        name: 'id',
                        type: { id: 'string', name: 'string' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_categories_name',
                        name: 'name',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_categories_color',
                        name: 'color',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_categories_userId',
                        name: 'userId',
                        type: { id: 'reference', name: 'reference' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_categories_icon',
                        name: 'icon',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'firestore_tags_collection',
                name: 'tags',
                x: 550,
                y: 100,
                fields: [
                    {
                        id: 'firestore_tags_id',
                        name: 'id',
                        type: { id: 'string', name: 'string' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_tags_name',
                        name: 'name',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_tags_color',
                        name: 'color',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'firestore_tags_usageCount',
                        name: 'usageCount',
                        type: { id: 'number', name: 'number' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: 'firestore_todos_user_rel',
                name: 'user_todos',
                sourceTableId: 'firestore_todos_collection',
                targetTableId: 'firestore_users_collection',
                sourceFieldId: 'firestore_todos_userId',
                targetFieldId: 'firestore_users_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'firestore_todos_category_rel',
                name: 'category_todos',
                sourceTableId: 'firestore_todos_collection',
                targetTableId: 'firestore_categories_collection',
                sourceFieldId: 'firestore_todos_categoryId',
                targetFieldId: 'firestore_categories_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'firestore_categories_user_rel',
                name: 'user_categories',
                sourceTableId: 'firestore_categories_collection',
                targetTableId: 'firestore_users_collection',
                sourceFieldId: 'firestore_categories_userId',
                targetFieldId: 'firestore_users_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
    },
};
