import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/employeedb.png';
import imageDark from '@/assets/templates/employeedb-dark.png';

const now = Date.now();

export const surrealdbTodosDb: Template = {
    slug: 'surrealdb-todos',
    name: 'SurrealDB Todos',
    shortDescription: 'Todo application schema for SurrealDB',
    description:
        'A comprehensive todo application schema for SurrealDB featuring users, todos, categories, and tags with modern multi-model database capabilities.',
    image,
    imageDark,
    tags: ['SurrealDB', 'NoSQL'],
    featured: true,
    diagram: {
        id: 'surrealdb_todos_db',
        name: 'surrealdb-todos',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.SURREALDB,
        tables: [
            {
                id: 'surrealdb_users_table',
                name: 'users',
                x: -250,
                y: 0,
                fields: [
                    {
                        id: 'surrealdb_users_id',
                        name: 'id',
                        type: { id: 'record', name: 'record' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_users_email',
                        name: 'email',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_users_name',
                        name: 'name',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_users_avatar',
                        name: 'avatar',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_users_created_at',
                        name: 'created_at',
                        type: { id: 'datetime', name: 'datetime' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_users_updated_at',
                        name: 'updated_at',
                        type: { id: 'datetime', name: 'datetime' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'surrealdb_users_email_idx',
                        name: 'email_unique',
                        unique: true,
                        fieldIds: ['surrealdb_users_email'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'surrealdb_todos_table',
                name: 'todos',
                x: 150,
                y: 0,
                fields: [
                    {
                        id: 'surrealdb_todos_id',
                        name: 'id',
                        type: { id: 'record', name: 'record' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_user_id',
                        name: 'user_id',
                        type: { id: 'record', name: 'record' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_title',
                        name: 'title',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_description',
                        name: 'description',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_completed',
                        name: 'completed',
                        type: { id: 'bool', name: 'bool' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_priority',
                        name: 'priority',
                        type: { id: 'int', name: 'int' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_category_id',
                        name: 'category_id',
                        type: { id: 'record', name: 'record' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_due_date',
                        name: 'due_date',
                        type: { id: 'datetime', name: 'datetime' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_tags',
                        name: 'tags',
                        type: { id: 'array', name: 'array' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_created_at',
                        name: 'created_at',
                        type: { id: 'datetime', name: 'datetime' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_updated_at',
                        name: 'updated_at',
                        type: { id: 'datetime', name: 'datetime' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'surrealdb_todos_user_idx',
                        name: 'user_id_idx',
                        unique: false,
                        fieldIds: ['surrealdb_todos_user_id'],
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_todos_category_idx',
                        name: 'category_id_idx',
                        unique: false,
                        fieldIds: ['surrealdb_todos_category_id'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'surrealdb_categories_table',
                name: 'categories',
                x: 150,
                y: 350,
                fields: [
                    {
                        id: 'surrealdb_categories_id',
                        name: 'id',
                        type: { id: 'record', name: 'record' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_categories_name',
                        name: 'name',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_categories_color',
                        name: 'color',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_categories_user_id',
                        name: 'user_id',
                        type: { id: 'record', name: 'record' },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'surrealdb_tags_table',
                name: 'tags',
                x: 550,
                y: 100,
                fields: [
                    {
                        id: 'surrealdb_tags_id',
                        name: 'id',
                        type: { id: 'record', name: 'record' },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_tags_name',
                        name: 'name',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'surrealdb_tags_color',
                        name: 'color',
                        type: { id: 'string', name: 'string' },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: 'surrealdb_todos_user_rel',
                name: 'user_todos',
                sourceTableId: 'surrealdb_todos_table',
                targetTableId: 'surrealdb_users_table',
                sourceFieldId: 'surrealdb_todos_user_id',
                targetFieldId: 'surrealdb_users_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'surrealdb_todos_category_rel',
                name: 'category_todos',
                sourceTableId: 'surrealdb_todos_table',
                targetTableId: 'surrealdb_categories_table',
                sourceFieldId: 'surrealdb_todos_category_id',
                targetFieldId: 'surrealdb_categories_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'surrealdb_categories_user_rel',
                name: 'user_categories',
                sourceTableId: 'surrealdb_categories_table',
                targetTableId: 'surrealdb_users_table',
                sourceFieldId: 'surrealdb_categories_user_id',
                targetFieldId: 'surrealdb_users_id',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
    },
};
